weightsite/tracker/urls.py
from django.urls import path
from . import views

app_name = 'tracker'

urlpatterns = [
    path('', views.weight_record_list, name='weight_record_list'),
    path('import/', views.import_weight_records, name='import_weight_records'),
    path('<slug:slug>/', views.weight_record_detail, name='weight_record_detail'),
]

weightsite/weightsite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('tracker/', include('tracker.urls', namespace='tracker')),
]

weightsite/tracker/models.py
from django.db import models

class WeightRecord(models.Model):
    weight = models.DecimalField(decimal_places=2, max_digits=5)
    body_fat = models.DecimalField(decimal_places=2, max_digits=5)
    date_recorded = models.DateField()
    slug = models.SlugField()
    time_created = models.DateTimeField(auto_now_add=True)

    objects = models.Manager()

    class Meta:
        ordering = ["-date_recorded"]
        indexes = [models.Index(fields=["-date_recorded"])]

weightsite/tracker/views.py
from requests import get
from django.shortcuts import render, redirect
from django.http import Http404
from .models import WeightRecord

def weight_record_list(request):
    weight_records = WeightRecord.objects.all()
    return render(request, 'tracker/weight_record/list.html', {'weight_records': weight_records})

def weight_record_detail(request, slug):
    try:
        weight_record = WeightRecord.objects.get(slug=slug)
    except WeightRecord.DoesNotExist:
        raise Http404("No Weight Record found!")
    return render(request, 'tracker/weight_record/detail.html', {'weight_record': weight_record})

def import_weight_records(request):
    if request.method == "POST":
        entries = fetch_libra_data("token")
        for entry in entries:
            WeightRecord.objects.create(**entry)
        return render(request, "tracker/weight_record/import.html")
    return render(request, "tracker/weight_record/import.html")

def fetch_libra_data(token):
    url = "https://api.libra-app.eu/values/weight"
    headers = {"Authorization": f"Bearer {token}"}
    response = get(url, headers=headers)
    response.raise_for_status()
    data = response.json()
    return [
        {"weight": entry["weight"], "body_fat": entry["body_fat"], "date_recorded": entry["date"][:10], "slug": entry["date"][:10]}
        for entry in data["values"]
    ]

weightsite/tracker/templates/tracker/base.html
{% load tracker_tags %}
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <title>{% block title %}{% endblock title %}</title>
        {% load bootstrap5 %}
        {% bootstrap_css %}
        {% bootstrap_javascript %}
    </head>
    <body>
        <nav class="navbar navbar-expand-sm bg-dark navbar-dark">
            <div class="container-fluid">
              <a class="navbar-brand" href="#">David Caldwell's Weight Loss Tracker</a>
            </div>
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="{% url "tracker:weight_record_list" %}">Records</a>
                </li>
               <li class="nav-item">
                    <a class="nav-link" href="{% url "tracker:import_weight_records" %}">Import</a>
                </li>
            </ul>
        </nav>
        
        <div class="row p-3">
            <div class=" w-75" id ="content">
                {% block content %}
                {% endblock content %}
            </div>
            <div class="p-2 w-25" id ="sidebar">
                <h3>Quick Stats</h3>
                <table class="table">
                    <tr>
                        <th>Latest Weight</th>
                        <td>{% latest_recorded_weight %}</td>
                    </tr>
                    <tr>
                        <th>Lowest Weight</th>
                        <td>{% lowest_recorded_weight %}</td>
                    </tr>
                    <tr>
                        <th>Highest Weight</th>
                        <td>{% highest_recorded_weight %}</td>
                    </tr>
                    <tr>
                        <th>Total Records</th>
                        <td>{% total_records %}</td>
                    </tr>
                </table>
            </div>
        </div>
    </body>
</html>

weightsite/tracker/templates/tracker/weight_record/detail.html
{% extends "tracker/base.html" %}

{% block title %}Weight Record {{weight_record.slug}}{% endblock title %}

{% block content %}
    <h1>Weight Record {{weight_record.slug}}</h1>
    <table class="table table-hover">
        <tr>
            <th>Weight (kg)</th>
            <td>{{weight_record.weight}}</td>
        </tr>
        <tr>
            <th>Body Fat (%)</th>
            <td>{{weight_record.body_fat}}</td>
        </tr>
        <tr>
            <th>Recorded</th>
            <td>{{weight_record.date_recorded}}</td>
        </tr>
        <tr>
            <th>Added</th>
            <td>{{weight_record.time_created}}</td>
        </tr>
    </table>
{% endblock content %}

weightsite/tracker/templates/tracker/weight_record/import.html
{% extends "tracker/base.html" %}

{% block title %}Import{% endblock title %}


{% block content %}
    <h1>Import Data From Libra</h1>
    <form method="POST">
        {% csrf_token %}
        <button type="submit">Import from Libra</button>
    </form>
{% endblock content %}

weightsite/tracker/templates/tracker/weight_record/list.html
{% extends "tracker/base.html" %}

{% block title %}Weight Records{% endblock title %}

{% block content %}
    <h1>Weight Records</h1>
    <div class="table-responsive-sm">  
        <table class="table table-hover">
            <thead>
                <tr>
                    <th scope="col">Date</th>
                    <th scope="col">Weight (kg)</th>
                    <th scope="col">Body Fat (%)</th>
                </tr>
            </thead>
            <tbody>
                {% for weight_record in weight_records %}
                <tr>
                    <td>
                        <a href="{% url 'tracker:weight_record_detail' weight_record.slug %}">
                            {{weight_record.slug}}
                        </a>
                    </td>
                    <td>{{weight_record.weight}}</td>
                    <td>{{weight_record.body_fat}}</td>
                <tr/>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock content %}